name: Teleport
version: '${project.version}'
main: com.arctic.Teleport
commands:
  tp:
    description: Teleport to a player
    permission: teleport.tp
  tpto:
    description: Teleport a player or all players to another player
    permission: teleport.tpto
  tphere:
    description: Teleport a player or all players at your position
    permission: teleport.tphere
  vanish:
    description: Hide you or the player from other players
    permission: teleport.vanish
  unvanish:
    description: Show you or the player to other players
    permission: teleport.unvanish
  tphelp:
    description: List of all teleport commands
    permission: teleport.help
